version: 1.0
groups:
  nox:
    help: A set of functionality ported from noxfile.py
    tasks:
      tests:
        help: Run nox tests
        backend: nox
        run: |
          import nox

          @nox.session(name="custom-name")
          def tests(session: nox.Session) -> None:
              """Run tests with pytest."""
              session.install("pytest")
              session.run("pytest", "--version")
      lint:
        help: Run nox tests
        backend: nox
        run: |
          import nox

          @nox.session
          def lint(session: nox.Session):
              """Run linters on the codebase."""
              session.install('flake8')
              session.run('flake8', '--version')

      all:
        help: Run nox tests
        hooks:
          pre-run:
            - task: nox.tests
            - task: nox.lint
