name: makim
channels:
  - nodefaults
  - conda-forge
dependencies:
  - bash
  - python
  - poetry >=1.5
  - nodejs
  - perl
  - r-base
  - sh
  - pip
  - pip:
      # note: workaround ci issue for macos
      - setuptools >= 40.8.0
      - wheel >=0.42.0
      # fix the distlib issue
      - paginate >=0.5
      # compose-go fails sometimes when installed by poetry
      - compose-go==2.33.1
