name: makim
channels:
  - nodefaults
  - conda-forge
dependencies:
  - bash
  - python 3.8.1  # min version supported
  - poetry >=1.5
  - nodejs
  - perl
  - r-base
  - sh
  - pip
  - pip:
    # note: workaround ci issue for macos
    - setuptools >= 40.8.0
